//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Gnucleus.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_GNUCLEUS_FORM               101
#define IDD_CONNECT                     102
#define IDD_FORM_CONNECT                103
#define IDD_VIEW_CONNECT                104
#define IDP_SOCKETS_INIT_FAILED         105
#define IDR_FRAMESHARE_TMPL             106
#define IDR_MAINFRAME                   127
#define IDR_GNUTYPE                     128
#define IDR_CONNECT                     129
#define IDR_DISCONNECT                  130
#define IDR_STATISTICS                  132
#define IDD_VIEW_STATISTICS             133
#define IDD_STAT_LOG                    134
#define IDR_TRASHED                     134
#define IDD_STAT_MAIN                   135
#define IDR_ROUTED                      135
#define IDR_BROADCASTED                 136
#define IDR_CONNECT_RCLICK              138
#define IDR_INCOMING                    139
#define IDR_STATISTICS_RCLICK           140
#define IDR_SETTINGS                    141
#define IDD_PREF_BANDWIDTH              142
#define IDD_PREF_SHARE                  144
#define IDD_PREF_CONNECT                145
#define IDR_TRAY_RCLICK                 146
#define IDR_TRAYON                      149
#define IDR_TRAYOFF                     150
#define IDD_PREF_LOCAL                  151
#define IDD_PREF_SEARCH                 152
#define IDD_PREF_TRANSFER               153
#define IDD_PREF_LOCAL_FIREWALL         154
#define IDD_PREF_CONNECT_SCREEN         155
#define IDD_PREF_SEARCH_SCREEN          156
#define IDD_VIEW_SHARE                  158
#define IDR_SHARE                       159
#define IDR_TRANSFERS                   162
#define IDD_TRANSFER_DOWN               163
#define IDD_TRANSFER_UP                 164
#define IDD_VIEW_TRANSFER               166
#define IDR_SHARE_RCLICK                168
#define IDR_UPLOAD_RCLICK               169
#define IDR_SCREENCONN_RCLICK           170
#define IDD_VIEW_SEARCH                 171
#define IDR_SEARCH                      172
#define IDD_SEARCH_RESULTS              174
#define IDD_SEARCH_ADVANCED             175
#define IDR_SEARCH_RCLICK               176
#define IDR_DOWNLOAD_RCLICK             177
#define IDD_TRANSFER_INFO               178
#define IDD_TRANSFER_UP_INFO            178
#define IDD_CONNECT_INFO                179
#define IDD_PREF_CONNECT_SERVERS        180
#define IDR_SERVERCONN_RCLICK           181
#define IDD_EVOLVE_TIMER                182
#define IDD_EVOLVE_MAIN                 183
#define IDD_STAT_DISTRIBUTION           184
#define IDD_STAT_PACKETS                185
#define IDD_STAT_BANDWIDTH              186
#define IDD_STAT_MEMORY                 187
#define IDD_SEARCH_INFO                 188
#define IDD_TRANSFER_DOWN_INFO          189
#define IDD_VIEW_CHAT                   190
#define IDR_CHAT                        191
#define IDR_CHAT_CONNECT_RCLICK         192
#define IDD_PREF_CHAT                   193
#define IDR_PREFCHAT_RCLICK             195
#define IDR_CHAT_USERS_RCLICK           196
#define IDR_BROWSER                     198
#define IDC_CURSOR1                     200
#define IDR_PARTIAL_RCLICK              201
#define IDR_WNDLIST_RCLICK              203
#define IDD_BUILD_MAP                   204
#define IDR_TRANSFERS_PARTIAL           206
#define IDR_TRANSFERS_UP                207
#define IDD_WINDOW_LIST                 208
#define IDR_TRANSFERS_DOWN              209
#define IDR_SEARCH_RESULTS              210
#define IDR_SEARCH_ADVANCED             211
#define IDR_SEARCH_BUTTON               212
#define IDD_DIALOG1                     213
#define IDD_PREF_PLUGINS                214
#define IDD_PREF_LOCAL_NETWORK          215
#define IDD_CONNECT_BASIC               216
#define IDD_CONNECT_ADVANCED            217
#define IDR_CONNECT_ADVANCED            220
#define IDR_CONNECT_BASIC               221
#define IDD_STAT_ERROR                  222
#define IDB_LOGO_BLACK                  223
#define IDB_SHARE                       224
#define IDB_SEARCH                      226
#define IDB_CHAT                        228
#define IDD_LAN_SETUP                   230
#define IDD_LAN_NEW                     231
#define IDR_SURF                        234
#define IDD_BROWSER_URL                 236
#define IDR_TOOLBAR_CHAT                237
#define IDR_TRAYOFF_LAN                 242
#define IDR_TRAYON_LAN                  243
#define IDD_TOOL_SCHEDULER              244
#define IDD_TOOL_ADDWEBCACHE            245
#define IDD_SHARE_INFO                  246
#define IDR_RESULT_COMPLETED            252
#define IDR_RESULT_DOWNLOADING          253
#define IDR_RESULT_NOHOSTS              254
#define IDR_RESULT_TRYING               255
#define IDB_TRANSFERS                   256
#define IDD_PREF_SEARCH_BLOCK           275
#define IDR_SEARCHEX_RCLICK             276
#define IDC_STATIC_AUTHOR               1000
#define IDC_EDIT_HOST                   1001
#define IDC_EDIT_PORT                   1002
#define IDC_EDIT_ALTNICK                1002
#define IDC_BUTTON_ADD                  1003
#define IDC_BUTTON_REMOVE               1004
#define IDC_LST_CONNECTED               1005
#define IDC_BUTTON_REFRESH              1005
#define IDC_LST_CACHE                   1006
#define IDC_LST_KNOWN                   1006
#define IDC_BUTTON_STOPGO               1006
#define IDC_BUTTON_PAUSEGO              1006
#define IDC_STATIC_EXIST                1007
#define IDC_STATIC_CONNECT              1008
#define IDC_STATIC_ADD                  1009
#define IDC_PSHEET_AREA                 1009
#define IDC_STATIC_HOST                 1010
#define IDC_STATIC_PORT                 1011
#define IDC_LIST_NODES                  1011
#define IDC_COMBO_HOST                  1012
#define IDC_LIST1                       1012
#define IDC_LIST_LOG                    1012
#define IDC_LIST_DIST                   1012
#define IDC_LIST_UPLOADS                1012
#define IDC_LIST_RESULTS                1012
#define IDC_LIST_SUMMARY                1012
#define IDC_LIST_USERS                  1012
#define IDC_LIST_PLUGINS                1012
#define IDC_LIST_KEYWORDS               1012
#define IDC_LIST_BLOCKED                1012
#define IDC_LIST_MEMORY                 1013
#define IDC_LIST_MEMORYZ                1013
#define IDC_LIST_ALTLOCS                1013
#define IDC_COMBO_SEARCH                1014
#define IDC_CHECK_PINGS                 1015
#define IDC_COMBO_SPEED                 1016
#define IDC_CHECK_PONGS                 1016
#define IDC_BUTTON_SEARCH               1017
#define IDC_CHECK_QUERIES               1017
#define IDC_COMBO_PROGRAM_MODE          1017
#define IDC_CHECK_QUERYHITS             1018
#define IDC_COMBO_EVOLVE                1019
#define IDC_CHECK_PUSHES                1020
#define IDC_CHECK_DROPPED               1021
#define IDC_CHECK_BAD                   1021
#define IDC_EDIT_BUFFSIZE               1022
#define IDC_STATIC_BUFFSIZE             1023
#define IDC_CHECK_GOOD                  1024
#define IDC_LIST_DATA                   1025
#define IDC_CHECK_IN                    1025
#define IDC_STATIC_SHARE                1026
#define IDC_CHECK_BAD2                  1026
#define IDC_CHECK_OUT                   1026
#define IDC_BUTTON_FLUSH                1031
#define IDC_STATIC_PACKREC              1034
#define IDC_STATIC_PACKSNT              1035
#define IDC_STATIC_PACKTOT              1036
#define IDC_STATIC_BYTEREC              1037
#define IDC_STATIC_BYTESNT              1038
#define IDC_STATIC_BYTETOT              1039
#define IDC_CHECK_TOTAL                 1041
#define IDC_CHECK_LIMIT_UP              1041
#define IDC_EDIT_TOTAL                  1042
#define IDC_EDIT_LIMIT_UP               1042
#define IDC_CHECK_DROP_DEAD             1043
#define IDC_CHECK_DROP_FRIENDS          1044
#define IDC_LIST_SCREEN                 1046
#define IDC_COMBO_RULE                  1047
#define IDC_RADIO_MODEL_INTERNET        1049
#define IDC_RADIO_MODEL_LAN             1050
#define IDC_RADIO_MODEL_PRIVATE         1051
#define IDC_CHECK_AUTOCONNECT           1052
#define IDC_CHECK_PATH                  1054
#define IDC_BUTTON_STOPSHARING          1055
#define IDC_CHECK_SENDRESULTS           1055
#define IDC_BUTTON_STARTSHARING         1056
#define IDC_CHECK_REPLYMAX              1056
#define IDC_EDIT_REPLY                  1057
#define IDC_BUTTON_RUNSELECTED          1058
#define IDC_BUTTON_CONFIGURE            1065
#define IDC_BUTTON_HELP                 1066
#define IDC_BUTTON_OPENDOWNLOADS        1066
#define IDC_BUTTON_CLEAR                1067
#define IDC_CHECK_ERROR                 1077
#define IDC_CHECK_ACTIVE                1078
#define IDC_CHECK_PENDING               1079
#define IDC_CHECK_COMPLETE              1080
#define IDC_LIST_DOWNLOADS              1081
#define IDC_PSHEET_TRANSFER             1082
#define IDC_LIST_CHUNKS                 1082
#define IDC_STATIC_SEARCH               1083
#define IDC_PSHEET_SEARCH               1088
#define IDC_CHECK_DOUBLECHECK           1089
#define IDC_BUTTON_DOWNLOAD             1090
#define IDC_CHECK_PORT                  1091
#define IDC_BUTTON_CONFIG               1091
#define IDC_CHECK_IP                    1094
#define IDC_EDIT_TIMEOUT                1095
#define IDC_CHECK_FIREWALL              1095
#define IDC_COMBO_SIZE                  1095
#define IDC_EDIT_PATH                   1096
#define IDC_EDIT_SPEED                  1097
#define IDC_EDIT_IP                     1101
#define IDC_BUTTON_CONFIG_SEARCH        1101
#define IDC_CHECK_SPEED                 1102
#define IDC_EDIT_FILE                   1102
#define IDC_BUTTON_SCREENHOSTS          1102
#define IDC_BUTTON_SCREENWORDS          1103
#define IDC_CHECKS_SCREEN               1106
#define IDC_CHECK_MIN_CONNECTS          1107
#define IDC_EDIT_REFINE                 1107
#define IDC_EDIT_MIN_CONNECTS           1108
#define IDC_EDIT_SIZE                   1108
#define IDC_CHECK_MAX_CONNECTS          1109
#define IDC_EDIT_MAX_CONNECTS           1110
#define IDC_CHECK_DISPLAY_SCREENED      1111
#define IDC_EDIT_DROP_FRIENDS           1111
#define IDC_EDIT_HANDSHAKE              1112
#define IDC_EDIT_LEAF_CONNECTS          1112
#define IDC_STATIC_NAME                 1113
#define IDC_STATIC_INDEX                1114
#define IDC_CHECK_MAX_DL                1115
#define IDC_EDIT_MAX_DL                 1116
#define IDC_STATIC_TIME                 1116
#define IDC_CHECK_EVOLVE                1117
#define IDC_CHECK_RETRY                 1117
#define IDC_CHECK_DROP_DL               1118
#define IDC_LIST_SERVERS                1118
#define IDC_EDIT_RETRY                  1118
#define IDC_EDIT_DROP_DL                1119
#define IDC_STATIC_VERSION              1119
#define IDC_CHECK_MAX_UL                1120
#define IDC_PROGRESS_TIMER              1120
#define IDC_LIST_SHARED                 1121
#define IDC_EDIT_MAX_UL                 1121
#define IDC_BUTTON1                     1121
#define IDC_BUTTON_OK                   1121
#define IDC_BUTTON_EXPAND               1121
#define IDC_ACHART                      1121
#define IDC_BUTTON_CLEARHISTORY         1121
#define IDC_BUTTON_START                1121
#define IDC_BUTTON_SHARED               1121
#define IDC_BUTTON_NEW                  1121
#define IDC_BUTTON_CLOSE                1121
#define IDC_BUTTON_UPDATE               1122
#define IDC_BUTTON_EVOVLE               1122
#define IDC_BUTTON_EVOLVE               1122
#define IDC_CHECK_DROP_UL               1123
#define IDC_BUTTON_CANCEL               1123
#define IDC_EDIT_DROP_UL                1124
#define IDC_STATIC_MESSAGE              1124
#define IDC_STATIC_STATUS               1124
#define IDC_BUTTON_CHAT                 1124
#define IDC_STATIC_FILENAME             1125
#define IDC_STATIC_LABEL                1125
#define IDC_STATIC_DESC                 1126
#define IDC_STATIC_PROGRESS             1126
#define IDC_BUTTON_TRANSFERS            1126
#define IDC_CHECK_NETWORK               1127
#define IDC_PROGRESS1                   1127
#define IDC_PROGRESS_UPDATE             1127
#define IDC_PROGRESS_CONNECT            1127
#define IDC_CHECK_LIMIT_DOWN            1127
#define IDC_PROGRESS_ADD                1127
#define IDC_EDIT_NETWORK                1128
#define IDC_STATIC_EVOLVE               1128
#define IDC_EDIT_LIMIT_DOWN             1128
#define IDC_LIST_BANDWIDTH              1129
#define IDC_CHECK_GROUPSIZE             1130
#define IDC_CHECK_GROUPNAME             1131
#define IDC_STATIC_SIZE                 1132
#define IDC_CHECK_RECURSE               1133
#define IDC_STATIC_SPEED                1133
#define IDC_STATIC_HOSTS                1134
#define IDC_CHECK_BUSY                  1135
#define IDC_TREE_CONNECTS               1136
#define IDC_EDIT_INPUT                  1138
#define IDC_RICHEDIT_CHAT               1139
#define IDC_STATIC_CONTACT1             1140
#define IDC_STATIC_USER                 1140
#define IDC_STATIC_CONTACT2             1141
#define IDC_STATIC_HAND                 1142
#define IDC_EDIT_SHARED                 1143
#define IDC_BUTTON_BROWSE               1144
#define IDC_EDIT_HOSTNAME               1145
#define IDC_BUTTON_BROWSE_PARTIALS      1145
#define IDC_STATIC_CHANNEL              1147
#define IDC_EDIT_NICK                   1149
#define IDC_COMBO_NETWORK               1150
#define IDC_EDIT_SERVER                 1151
#define IDC_CHECK_DEFNETWORK            1152
#define IDC_CHECK_PREFCHAN              1153
#define IDC_EDIT_PREFCHAN               1154
#define IDC_STATIC_SERVERS              1155
#define IDC_BUTTON_RESEARCH             1158
#define IDC_BUTTON_DELETE               1159
#define IDC_LIST_PARTIALS               1160
#define IDC_EDIT_KEYWORDS               1161
#define IDC_BUTTON_BUILD                1163
#define IDC_STATIC_NODES                1164
#define IDC_CHECK_SIZENODES             1165
#define IDC_EDIT_HOPS                   1166
#define IDC_CHECK_SAVEPARTIALS          1167
#define IDC_CHECK_SHAPENODES            1167
#define IDC_BUTTON_READ                 1168
#define IDC_EDIT_HEIGHT                 1169
#define IDC_EDIT_WIDTH                  1170
#define IDC_PARTIALS_COLOR              1170
#define IDC_SHARED_COLOR                1171
#define IDC_EDIT_HASH                   1171
#define IDC_USED_COLOR                  1172
#define IDC_EDIT_DEAD                   1172
#define IDC_EDIT_HASH2                  1172
#define IDC_EDIT_BITPRINTHASH           1172
#define IDC_FREE_COLOR                  1173
#define IDC_PARTIALS_TXT                1174
#define IDC_SHARED_TXT                  1175
#define IDC_COMBO_STARTUP               1175
#define IDC_USED_TXT                    1176
#define IDC_BUTTON_STOP                 1176
#define IDC_FREE_TXT                    1177
#define IDC_RECYCLE_COLOR               1178
#define IDC_RECYCLE_TXT                 1179
#define IDC_BUTTON_ABOUT                1179
#define IDC_EMPTY_RECYCLE               1180
#define IDC_STATIC_ATTEMPTS             1180
#define IDC_DOWNLOADING_COLOR           1181
#define IDC_CHECK_TRAYMIN               1181
#define IDC_DOWNLOADING_TXT             1182
#define IDC_CHECK_TRAYCLOSE             1182
#define IDC_WHENCOMPLET_TXT             1183
#define IDC_EDIT_LANNAME                1183
#define IDC_EXPLORE_PARTIALS            1184
#define IDC_CHECK_UPDATESERVER          1184
#define IDC_DRIVE_NAME                  1185
#define IDC_CHECK_IRCSERVER             1185
#define IDC_EXPLORE                     1186
#define IDC_EDIT_IRCSERVER              1186
#define IDC_TOTALS_TXT                  1187
#define IDC_EDIT_UPDATESERVER           1187
#define IDC_CHECK_SUPERNODE             1187
#define IDC_WARNING                     1188
#define IDC_CHECK_LANNAME               1188
#define IDC_WINDOW_TABS                 1189
#define IDC_PSHEET_CONNECT              1189
#define IDC_LIST_ERROR                  1193
#define IDC_STATIC_LOGO                 1194
#define IDC_STATIC_SHARED               1198
#define IDC_STATIC_TRANSFERS            1199
#define IDC_STATIC_CHAT                 1200
#define IDC_LIST_LAN                    1202
#define IDC_BUTTON_JOIN                 1203
#define IDC_EDIT_NAME                   1204
#define IDC_EDIT_IRC                    1205
#define IDC_CHECK_MAPPING               1205
#define IDC_CHECK_MULTISOURCE           1207
#define IDC_EDIT_URL                    1209
#define IDC_BUTTON_GO                   1210
#define IDC_STATIC_TEMP1                1218
#define IDC_STATIC_TEMP2                1219
#define IDC_STATIC_TEMP3                1220
#define IDC_STATIC_TEMP4                1221
#define IDC_STATIC_TEMP5                1222
#define IDC_STATIC_TEMP6                1223
#define IDC_SLIDER_USAGE                1223
#define IDC_STATIC_TEMP7                1224
#define IDC_STATIC_TEMP8                1225
#define IDC_STATIC_TEMP9                1226
#define IDC_BUTTON_STOPSEARCH           1228
#define IDC_CHECK_DEDICATED             1229
#define IDC_STATIC_USAGE                1230
#define IDC_CHECK_SCHED_ACTIVATED       1231
#define IDC_SCHED_INACTIVE              1236
#define IDC_SCHED_ACTIVE                1238
#define IDC_STATIC_SCHED_FRAME          1239
#define IDC_STATIC_SCHED_CONNECT        1240
#define IDC_STATIC_SCHED_DISCONNECT     1241
#define IDC_STATIC_BITPRINTHASH         1244
#define IDC_STATIC_SHA1HASH             1245
#define IDC_EDIT_NEWCACHE               1245
#define IDC_CHECK_STOPHASHING           1246
#define IDC_EDIT_SHA1HASH               1248
#define IDC_EDIT_INDEX                  1249
#define IDC_BUTTON_VIEWTRANSFERS        1249
#define IDC_BUTTON_OPENPARTIALS         1250
#define IDC_EDIT_MAXLEAF                1251
#define IDC_MEDIA                       1252
#define IDC_STOP                        1253
#define IDC_PAUSE                       1254
#define IDC_REW                         1255
#define IDC_FF                          1256
#define IDC_SLIDER_POS                  1257
#define IDC_FILE_INFO                   1258
#define IDC_PLAY                        1259
#define IDC_CHECK1                      1260
#define IDC_CHECK_IDENT_DISABLE         1261
#define IDC_EDIT2                       1263
#define IDC_EDIT_REASON                 1263
#define IDC_STATIC_STARNOTE             1266
#define IDC_SLIDER_VOL                  1267
#define IDC_EDIT_PARTIALS               1268
#define IDC_STATIC_GNUCDNA              1269
#define IDC_STATIC_DNALICENSE           1270
#define IDC_PREF_TREE                   5000
#define ID_FILE_CONFIG                  32774
#define ID_VIEW_STATISTICS              32775
#define ID_VIEW_CONNECTIONS             32776
#define ID_VIEW_TRANSFERS               32777
#define ID_FILE_AUTOCONNECT             32778
#define ID_WINDOW_CLOSEALL              32780
#define ID_FILE_LOAD_CONFIG             32781
#define ID_CONNECT_CLOSE                32782
#define ID_VIEW_NODEHUNTER              32784
#define ID_FILE_LOAD_NODES              32785
#define ID_FILE_DISCONNECT              32786
#define ID_VIEW_SETTINGS                32787
#define ID_LSTCONNECT_LOG               32797
#define ID_LSTCONNECT_DISCONNECT        32798
#define ID_LSTCONNECT_REFRESH           32799
#define ID_LSTKNOWN_CONNECT             32800
#define ID_LSTKNOWN_REMOVE              32801
#define ID_LSTNODES_DISCONNECT          32802
#define ID_VIEW_PREFERENCES             32807
#define ID_VIEW_SHARE                   32809
#define ID_LSTSEARCHEX_BLOCK            32813
#define ID_LSTSHARED_STOP               32814
#define ID_LSTUPLOADS_REMOVE            32815
#define ID_SCREENCONN_REMOVE            32816
#define ID_LSTSEARCH_DOWNLOAD           32817
#define ID_LSTDOWNLOADS_REMOVE          32818
#define ID_LSTDOWNLOADS_START           32819
#define ID_LSTDOWNLOADS_STOP            32820
#define ID_LSTDOWNLOADS_INFO            32821
#define ID_LSTUPLOADS_INFO              32822
#define ID_LSTCONNECT_INFO              32823
#define ID_LSTNODES_INFO                32824
#define D_APP_SUPPORT                   32825
#define D_APP_BUG                       32826
#define ID_APP_VERSIONCHECK             32827
#define ID_HELP_CHANGELOG               32828
#define ID_HELP_BUG                     32829
#define ID_HELP_VERSIONCHECK            32830
#define ID_LSTSHARED_RUN                32831
#define ID_LSTUPLOADS_RUN               32832
#define ID_LSTDOWNLOADS_RUN             32833
#define ID_SERVERCONN_REMOVE            32834
#define ID_LSTSEARCH_INFO               32835
#define ID_LSTDOWNLOADS_NEXT            32836
#define ID_LSTNODES_REFRESH             32837
#define ID_VIEW_CHAT                    32838
#define ID_LSTDOWNLOADS_RESEARCH        32839
#define ID_CHAT_LSTCONNECTED_CLOSE      32840
#define ID_PREFCHAT_REMOVE              32841
#define ID_CHAT_WHOIS                   32842
#define ID_CHAT_VERSION                 32843
#define ID_VIEW_MEDIA_TOOLBAR           32844
#define ID_CHAT_CONTROL_OP              32845
#define ID_CHAT_CONTROL_DEOP            32846
#define ID_CHAT_CONTROL_KICK            32847
#define ID_CHAT_CONTROL_BAN             32848
#define ID_CHAT_PRIVATE                 32849
#define ID_HELP_MAP                     32850
#define ID_FILE_MAP                     32850
#define ID_OPTIONS_PARTIAL_RESEARCH     32851
#define ID_OPTIONS_PARTIAL_EDITKEYWORD  32852
#define ID_OPTIONS_PARTIAL_DELETE       32853
#define ID_OPTIONS_PARTIAL_RUN          32854
#define ID_TOOLS_DRIVEINFO              32855
#define ID_GOTO_SEARCH                  32856
#define ID_VIEW_WINDOWLIST              32857
#define ID_BUTTON32857                  32857
#define ID_WINDOW_LIST                  32857
#define ID_BUTTON32858                  32858
#define ID_BUTTON32859                  32859
#define ID_WNDLIST_MAX                  32860
#define ID_WNDLIST_CLOSE                32861
#define ID_WNDLIST_MIN                  32862
#define ID_WNDLIST_SHOW                 32863
#define ID_HELP_HOMEPAGE                32864
#define ID_SURF_BACK                    32865
#define ID_SURF_FORWARD                 32866
#define ID_SURF_STOP                    32867
#define ID_SURF_REFRESH                 32868
#define ID_SURF_HOME                    32869
#define ID_VIEW_BROWSER                 32870
#define ID_CHAT_CONNECT                 32871
#define ID_CHAT_DISCONNECT              32872
#define ID_CHAT_PREFS                   32873
#define ID_CHAT_COLORS                  32874
#define ID_CHAT_HELP                    32876
#define ID_CHAT_REMOTE                  32877
#define ID_CHAT_ALIAS                   32878
#define ID_TOOLS_BROWSENETWORK          32879
#define ID_TOOLS_SCHEDULER              32880
#define ID_HELP_REPORTGNUCACHE          32882
#define ID_LSTSHARED_INFO               32883
#define ID_LSTSEARCH_CANCEL             32884
#define ID_PLACE_STATUS                 32885
#define ID_PLACE_MEDIA                  32886
#define IDS_Erro_Funcao_nao_encontrada  32887
#define IDS_INFO                        32888
#define IDS_OK                          32889
#define IDS_Cancelar                    32890
#define IDS_STATUS_NOTIMPL              32891
#define IDS_DEFAULTDOC                  32892
#define IDS_DEFAULTAPP                  32893
#define IDS_STATUS_BADREQUEST           32894
#define IDS_STATUS_NOTFOUND             32895
#define IDS_SERVER_NAME                 32896
#define IDS_STATUS_FORBIDDEN            32897
#define IDS_STATUS_OK                   32898
#define IDS_STATUS_NOTMODIFIED          32899
#define IDS_STATUS_SVCUNAVAIL           32900
#define IDS_DIRMASK                     32901
#define IDS_CONTENTS_PRE                32902
#define IDS_CONTENTS_POST               32903
#define IDS_CONTENTS_DESC               32904
#define IDS_ICON_BLANK                  32905
#define IDS_CONTENTS_HEADING            32906
#define IDS_CONTENTS_EMPTY              32907
#define IDS_CONTENTS_FOOTER             32908
#define IDS_ICON_PARENT                 32909
#define IDS_CONTENTS_PARENT             32910
#define IDS_CONTENTS_NOTE               32912
#define IDS_ICON_FOLDER                 32913
#define IDS_ICON_FILE                   32914
#define IDS_CONTENTS_FORMAT             32915
#define IDS_FILETIMEFMT                 32916
#define IDS_HTTPTIME                    32917
#define IDS_APP_CGI                     32918
#define IDS_APP_ISAPI                   32919
#define IDS_STATUS_MOVEDTEMP            32920
#define IDS_CONFIG                      32921
#define IDS_VERSION                     61216
#define ID_INDICATOR_RECV               61217
#define ID_INDICATOR_SEND               61218

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        277
#define _APS_NEXT_COMMAND_VALUE         32924
#define _APS_NEXT_CONTROL_VALUE         1271
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
